/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class helper_TEAEncryption */

#ifndef _Included_helper_TEAEncryption
#define _Included_helper_TEAEncryption
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     helper_TEAEncryption
 * Method:    encrypt
 * Signature: ([I[I)V
 */
JNIEXPORT void JNICALL Java_helper_TEAEncryption_encrypt
  (JNIEnv *, jobject, jintArray, jintArray);

/*
 * Class:     helper_TEAEncryption
 * Method:    decrypt
 * Signature: ([I[I)V
 */
JNIEXPORT void JNICALL Java_helper_TEAEncryption_decrypt
  (JNIEnv *, jobject, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
