/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TEAEncryption */

#ifndef _Included_TEAEncryption
#define _Included_TEAEncryption
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TEAEncryption
 * Method:    encrypt
 * Signature: ([I[I)V
 */
JNIEXPORT void JNICALL Java_TEAEncryption_encrypt
  (JNIEnv *, jobject, jintArray, jintArray);

/*
 * Class:     TEAEncryption
 * Method:    decrypt
 * Signature: ([I[I)V
 */
JNIEXPORT void JNICALL Java_TEAEncryption_decrypt
  (JNIEnv *, jobject, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
